default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %> # Render will provide this in the environment
  template: template0

development:
  <<: *default
  database: stripe_app_development
  # Optional: Render will handle connection details via DATABASE_URL,
  # so the following can be removed if DATABASE_URL is set correctly.
  # username: <%= ENV['DATABASE_USERNAME'] %>
  # password: <%= ENV['DATABASE_PASSWORD'] %>
  # host: <%= ENV['DATABASE_HOST'] %>

test:
  <<: *default
  database: stripe_app_test
  username: ror
  password: 1234
  host: localhost

production:
  <<: *default
  database: stripe_app_production
  # Use DATABASE_URL in production as well.
  # username: <%= ENV['DATABASE_USERNAME'] %>
  # password: <%= ENV['DATABASE_PASSWORD'] %>
  # host: <%= ENV['DATABASE_HOST'] %>
